env:
  global:
    - CC_TEST_REPORTER_ID=b276454e47b0c8139bc27010eb9ac63b23bec7068e415241bbcf1a9b57dc7f5c
language: node_js
node_js:
  - "8.11.4"
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script: yarn test:coverage
after_script:
  - cd ..
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT